import ApplicationLayout from '@/layouts/ApplicationLayout'
import './globals.css'
import "./styles.css"

export const metadata = {
  title: 'U-Social',
  description: 'USocial Media Web App Generated by create-next-app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <script src="https://kit.fontawesome.com/20fd113779.js" crossOrigin="anonymous"></script>
      </head>
      <body>
        <ApplicationLayout>
          {children}
        </ApplicationLayout>
      </body>
    </html>
  )
}
