import ApplicationLayout from '@/layouts/ApplicationLayout'
import './globals.css'

export const metadata = {
  title: 'U-Social',
  description: 'USocial Media Web App Generated by create-next-app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ApplicationLayout>
          {children}
        </ApplicationLayout>
      </body>
    </html>
  )
}
